spring:
    profiles: test
profilename: test-YAML
name: Ivan
surname: Ivanov
#locale: ru_RU
locale: en_US
 
---
spring:
    profiles: prod
profilename: prod-YAML
name: Petr
surname: Petrov
