spring.banner.location: "classpath:abr_banner.txt"

spring:
    profiles: test
profilename: test-YAML
name: Ivan
surname: Ivanov
qfilename: questions
locale: en_US
 
---
spring:
    profiles: prod
profilename: prod-YAML
name: Petr
surname: Petrov
qfilename: questions
locale: ru_RU