#spring.banner.location: "classpath:abr_banner_en.txt"

spring:
    profiles: test
profilename: test-YAML
spring.banner.location: "classpath:abr_banner_en.txt"
name: Ivan
surname: Ivanov
qfilename: questions
locale: en_US
 
---
spring:
    profiles: prod
profilename: prod-YAML
spring.banner.location: "classpath:abr_banner_ru.txt"
name: Петр
surname: Петров
qfilename: questions
locale: ru_RU