spring:
  profiles: cloud
  data:
    mongodb:
       host: ds020208.mlab.com
       port: 20208
       database: tsstarter
       username: tsstarter
       password: tsstarter00

---
spring:
  profiles: abr
  data:
    mongodb:
       host: vm-dit-lvov.abr.loc
       port: 8200
       database: books
