DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(AUTHORID INT PRIMARY KEY, AUTHORNAME VARCHAR(255));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(GENREID INT PRIMARY KEY, GENRENAME VARCHAR(255));
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(BOOKID INT PRIMARY KEY, BOOKNAME VARCHAR(255), AUTHORID INT, GENREID INT);
