spring:
  profiles: abr
  data:
    mongodb:
      host: vm-dit-lvov.abr.loc 
      port: 8200
      database: mean-angular6
---
spring:
  profiles: cloud
  data:
    mongodb:
      host: ds020208.mlab.com
      port: 20208
      database: tsstarter
      username: tsstarter
      password: tsstarter00
---
spring:
  profiles: udelny
  data:
    mongodb:
      host: vm-oel75
      port: 27017
      database: mean-angular6
---
spring:
  profiles: udelny-docker
  data:
    mongodb:
      host: vm-oel75
      port: 27000
      database: mean-angular6
