spring:
  profiles: abr
  data:
    mongodb:
      host: vm-dit-lvov.abr.loc 
      port: 8200
      database: mean-angular6
---
spring:
  profiles: cloud
  data:
    mongodb:
      host: ds020208.mlab.com
      port: 20208
      database: tsstarter
      username: tsstarter
      password: tsstarter00
security_config: prod
---
spring:
  profiles: udelny
  data:
    mongodb:
      host: vm-oel75
      port: 27017
      database: mean-angular6
# do not use 2-space indent before security-config parameter below
security_config: prod
#security-config: angular-live-dev
---
spring:
  profiles: abr-docker
  data:
    mongodb:
      host: orsapps-tst.abr.loc
      port: 27017
      database: mean-angular6
  rabbitmq:
    host: orsapps-tst.abr.loc
    port: 5672
---
spring:
  profiles: test
  data:
    mongodb:
      database: mean-angular6
